[workspace]
members = ["crates/*", "tools/visualizer"]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "MIT"
authors = ["zifeng <zifeng.1024@gmail.com>"]
repository = "https://github.com/popsicle-lab/intent-lang"
homepage = "https://github.com/popsicle-lab/intent-lang"
keywords = ["intent", "formal-methods", "smt", "requirements", "verification"]
categories = ["development-tools", "parser-implementations"]

[workspace.dependencies]
intent-lang-syntax = { version = "0.1.3", path = "crates/intent-lang-syntax" }
intent-lang-core = { version = "0.1.3", path = "crates/intent-lang-core" }
